let womenData=[
    {
        "name": "Floral Maxi Dress",
        "person":"women",
        "category": "dresses",
        "price": 49.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "Multi-color",
        "stock": 100,
        "rating": 4.7,
        "description": "A beautiful floral maxi dress that flows elegantly, perfect for summer outings.",
        "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWF4aSUyMGRyZXNzfGVufDB8fDB8fHww"
    },
    {
        "name": "High-Waisted jeans",
        "person":"women",
        "category": "jeans",
        "price": 42.99,
        "sizes": ["24", "26", "28", "30"],
        "color": "Dark Blue",
        "stock": 120,
        "rating": 4.5,
        "description": "Stylish high-waisted jeans that accentuate your figure and provide comfort.",
        "image": "https://media.istockphoto.com/id/154352962/photo/edgy-beauty-leaning-on-a-bench.jpg?s=612x612&w=0&k=20&c=5N6KhVoN7JYsYgBmBMSHW3u6YTWa0h60Dr0Z1WrRmt4="
    },
    {
        "name": "Silk Blouse",
        "person":"women",
        "category": "tops",
        "price": 39.99,
        "sizes": ["S", "M", "L"],
        "color": "White",
        "stock": 80,
        "rating": 4.6,
        "description": "Elegant silk blouse that adds a touch of sophistication to any outfit.",
        "image": "https://media.istockphoto.com/id/1360648166/photo/classic-business-style-of-clothing.webp?a=1&b=1&s=612x612&w=0&k=20&c=QZrzfDc1WmpfW7gVgPAvNXnmFmylvhtmrHito_6ogFE="
    },
    {
        "name": "Leather Biker Jacket",
        "person":"women",
        "category": "jackets",
        "price": 129.99,
        "sizes": ["S", "M", "L"],
        "color": "Black",
        "stock": 45,
        "rating": 4.8,
        "description": "Edgy leather biker jacket, perfect for layering over casual looks.",
       "image": "https://media.istockphoto.com/id/614969920/photo/woman-in-the-street-cafe.jpg?s=612x612&w=0&k=20&c=YMzsmMDaHysjn_DT3_0yMlo9XNY40c3h93hAiG7hIts="
    },
    {
        "name": "Cozy Knit Sweater",
        "person":"women",
        "category": "jackets",
        "price": 34.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "Cream",
        "stock": 90,
        "rating": 4.4,
        "description": "Warm and cozy knit sweater ideal for colder months.",
        "image": "https://media.istockphoto.com/id/1275848548/photo/young-beautiful-woman-wearing-sweater-and-shorts.jpg?s=612x612&w=0&k=20&c=eNB6PCNPDSh33RHxVSRdWFZx5SozmvuJmmfYAuK67Sc="
    },
    {
        "name": "Tailored Trousers",
        "person":"women",
        "category": "pants",
        "price": 49.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "Black",
        "stock": 70,
        "rating": 4.5,
        "description": "Chic tailored trousers that provide a polished look for the office.",
        "image": "https://media.istockphoto.com/id/1018293976/photo/attractive-fashionable-woman-posing-in-white-trendy-sweater-beige-pants-and-autumn-heels-on.webp?a=1&b=1&s=612x612&w=0&k=20&c=Bw-VipXy6NZ5d09wrswFdMlftcB02ItY_ZctVBWgexI="
    },
    {
        "name": "Casual Denim Jacket",
        "person":"women",
        "category": "jackets",
        "price": 59.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "Light Blue",
        "stock": 60,
        "rating": 4.6,
        "description": "Classic denim jacket for a relaxed and stylish look.",
        "image": "https://media.istockphoto.com/id/1349960077/photo/rocking-denim-wear.jpg?s=612x612&w=0&k=20&c=fB3hzEp_aOF2lk6QmMW4sUGDiQhhQkgwQ9OOO3VlDHc="
    },
    {
        "name": "A-Line Skirt",
        "person":"women",
        "category": "skirts",
        "price": 29.99,
        "sizes": ["S", "M", "L"],
        "color": "Navy Blue",
        "stock": 85,
        "rating": 4.5,
        "description": "Flattering A-line skirt that is versatile for both casual and formal wear.",
        "image": "https://media.istockphoto.com/id/621468074/photo/attractive-sexy-woman-wearing-black-a-line-skirt-holding-green.webp?a=1&b=1&s=612x612&w=0&k=20&c=EpS9qH1jHISOpey6hCuk93lFIwdRqFmlnTghzIzRLEY="
    },
    {
        "name": "Sporty Joggers",
        "person":"women",
        "category": "pants",
        "price": 27.99,
        "sizes": ["S", "M", "L"],
        "color": "Black",
        "stock": 95,
        "rating": 4.4,
        "description": "Comfortable joggers designed for workouts and casual days.",
        "image": "https://media.istockphoto.com/id/1007730100/photo/challenging-herself.webp?a=1&b=1&s=612x612&w=0&k=20&c=vH5HoLoB2GV07bvSiZlcaEV-vz6bjDR9XY6QuNeqr5E="
    },
    {
        "name": "Chiffon Wrap Dress",
        "person":"women",
        "category": "dresses",
        "price": 45.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "Pink",
        "stock": 75,
        "rating": 4.8,
        "description": "Lightweight chiffon wrap dress perfect for day or evening wear.",
        "image": "https://media.istockphoto.com/id/1412018775/photo/serie-of-studio-photos-of-young-female-model-in-black-viscose-wrap-dress.webp?a=1&b=1&s=612x612&w=0&k=20&c=i05eb2ar2XL6ngVtSfe_gkOtnvXVHfl17Pno0BWBB5M="
    },
    {
        "name": "Basic Tank Top",
        "person":"women",
        "category": "tops",
        "price": 14.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "Black",
        "stock": 150,
        "rating": 4.2,
        "description": "Essential black tank top, a versatile piece for layering.",
        "image": "https://media.istockphoto.com/id/1154664345/photo/happy-young-fashion-woman-in-gray-crop-top-and-skirt-suit-leaning-on-railing.jpg?s=612x612&w=0&k=20&c=4VmziOqxpvZQP5Nm8BqZ2qL0u13hnzfa-O7VDq-bfa0="
    },
    {
        "name": "Fit and Flare Dress",
        "person":"women",
        "category": "dresses",
        "price": 52.99,
        "sizes": ["S", "M", "L"],
        "color": "Red",
        "stock": 50,
        "rating": 4.6,
        "description": "Stylish fit and flare dress that flatters all body types.",
        "image": "https://media.istockphoto.com/id/2150387123/photo/smiling-woman-in-floral-mini-dress-and-straw-hat-on-sunny-beach-fashionable-female-enjoys.webp?a=1&b=1&s=612x612&w=0&k=20&c=RvbU5gqfK9NfeoLBgYy1Wqe3SM34R5Gamfk5BgRcG2g="
    },
    {
        "name": "Graphic Tee",
        "person":"women",
        "category": "shirts",
        "price": 19.99,
        "sizes": ["S", "M", "L", "XL"],
        "color": "White",
        "stock": 130,
        "rating": 4.5,
        "description": "Trendy graphic tee that makes a statement in casual style.",
        "image": "https://media.istockphoto.com/id/1607497623/photo/excited-woman-showing-her-white-mockup-t-shirt.webp?a=1&b=1&s=612x612&w=0&k=20&c=d6KoG5r3iPaFzFqvhZPMTggZKxoNEDtrlTFv-acbfOQ="
    },
    {
        "name": "Lightweight Cardigan",
        "person":"women",
        "category": "jackets",
        "price": 29.99,
        "sizes": ["S", "M", "L"],
        "color": "Gray",
        "stock": 100,
        "rating": 4.3,
        "description": "Perfect for layering, this lightweight cardigan adds warmth without bulk.",
        "image": "https://media.istockphoto.com/id/887437690/photo/worried-pensive-teen-looking-down.webp?a=1&b=1&s=612x612&w=0&k=20&c=oOxbu67shhQYkx2hbzo_vV30y9QcByGddTPE3wggnL4="
    },
    {
        "name": "Wrap Front Top",
        "person":"women",
        "category": "tops",
        "price": 34.99,
        "sizes": ["S", "M", "L"],
        "color": "White",
        "stock": 85,
        "rating": 4.6,
        "description": "Chic wrap front top that is perfect for a day at the office or a night out.",
        "image": "https://images.unsplash.com/photo-1485145782098-4f5fd605a66b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dG9wJTIwZm9yJTIwd29tZW58ZW58MHx8MHx8fDA%3D"
    },
    {
        "name": "Pleated Midi Skirt",
        "person":"women",
        "category": "skirts",
        "price": 36.99,
        "sizes": ["S", "M", "L"],
        "color": "Black",
        "stock": 70,
        "rating": 4.4,
        "description": "Elegant pleated midi skirt that moves beautifully with every step.",
        "image": "https://media.istockphoto.com/id/2129639901/photo/serie-of-studio-photos-of-female-model-in-all-black-look.jpg?s=612x612&w=0&k=20&c=jbIKYdK6ao6ihCg0MpPcZ5Oaz-iMicv7DsmQ1CJLwFw="
    },
    {
        "name": "Casual Chambray Shirt",
        "person":"women",
        "category": "tops",
        "price": 29.99,
        "sizes": ["S", "M", "L"],
        "color": "Light Blue",
        "stock": 90,
        "rating": 4.5,
        "description": "Classic chambray shirt, perfect for casual outings or layered looks.",
        "image": "https://media.istockphoto.com/id/481292763/photo/portrait-of-young-female-architect.jpg?s=612x612&w=0&k=20&c=28wTNcAeYmBpx5kSSy3abcgc5yT3CKhkHtEDkrmGrT4="
    },
    {
        "name": "Patterned Palazzo pants",
        "person":"women",
        "category": "pants",
        "price": 39.99,
        "sizes": ["S", "M", "L"],
        "color": "Multi-color",
        "stock": 75,
        "rating": 4.6,
        "description": "Flowy patterned palazzo pants that offer comfort and style.",
        "image": "https://media.istockphoto.com/id/958829764/photo/beautiful-young-redhead-woman-with-long-curly-ginger-hair-wearing-trendy-clothes.jpg?s=612x612&w=0&k=20&c=ECNn8zwhRmr3TmwQRpTHn5ONlGFFdEgztFgLPPyH6vY="
    },
    {
        "name": "Linen Sundress",
        "person":"women",
        "category": "dresses",
        "price": 44.99,
        "sizes": ["S", "M", "L"],
        "color": "Yellow",
        "stock": 60,
        "rating": 4.8,
        "description": "Lightweight linen sundress perfect for sunny days at the beach or picnics.",
        "image": "https://media.istockphoto.com/id/530182709/photo/young-sensual-cowgirl-leans-against-stable-gates.jpg?s=612x612&w=0&k=20&c=sRl2tvCBvY77VI_WNexaclOkiXKv6Lz9OYK18wFkBVw="
    },
    {
        "name": "Sporty Underneath",
        "person":"women",
        "category": "tops",
        "price": 69.99,
        "sizes": ["S", "M", "L"],
        "color": "Olive",
        "stock": 40,
        "rating": 4.5,
        "description": "Stylish belted utility jacket that combines fashion with functionality.",
        "image": "https://media.istockphoto.com/id/170025581/photo/bra-and-breasts-close-up.jpg?s=612x612&w=0&k=20&c=bpjsvSd61g-APdYTjh4SJPCZt3njfiDTHiSSO7jbJ2c="
    }
]

module.exports={data:womenData};